[package]
name = "multithreading"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
crossbeam = { workspace = true }

[lints]
workspace = true
